### ISSUE TITLE
Format on save

### ISSUE THREAD

**Issue by isaacvando** [ivan-demchenko/roc-vscode-unofficial#11]
Thanks for making this!

This is just a feature idea: format on save would be cool.

**Comment by raqystyle** [comment]
Hi @isaacvando
Sorry for the delay. Thanks to @ayazhafiz and this PR (#12) this feature request might land on this extension pretty soon. Stay tuned!

**Comment by rtfeldman** [comment]
Also relevant: https://github.com/roc-lang/roc/pull/5917
