### ISSUE TITLE
Publish extension to Open VSX

### ISSUE THREAD

**Issue by george-hopkins** [ivan-demchenko/roc-vscode-unofficial#18]
It would be great if the extension would be available on https://open-vsx.org as well. It would benefit users which are using VS Code alternatives (Codium, Theia).

Instructions to get started: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by joe2xyz** [comment]
Open-VSX is the only way to find+install the extension in VSCodium. Please add it.
.
.
![image](https://github.com/ivan-demchenko/roc-vscode-unofficial/assets/122208221/9099ee99-5e96-46a1-a826-977f0d48f4ac)

**Comment by ivan-demchenko** [comment]
Hello @george-hopkins and @joe2xyz ,
Sorry for the delay with this issue. I've set up the publishing process to OVSX, but now I'm [claiming](https://github.com/EclipseFdn/open-vsx.org/issues/2265) ownership of my namespace.

P.S. Enjoy the festive time! 🎄 🎁

**Comment by joe2xyz** [comment]
@ivan-demchenko do not apologize for delays. It's up to you if you want to do it at all and if you do, the delay is no issue.

Thank you VERY MUCH!

Enjoy the holiday! Thank you!
